# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.TextField()),
                ('condition', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.FileField(default=None, upload_to='')),
                ('name', models.TextField()),
                ('set', models.TextField()),
                ('rarity', models.TextField()),
                ('format', models.TextField()),
                ('color', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_list', models.ManyToManyField(to='CardCrab.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardDetails'),
        ),
    ]
