# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CardColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_art', models.URLField()),
                ('back_art', models.URLField()),
                ('name', models.TextField()),
                ('color', models.ManyToManyField(to='CardCrab.CardColor')),
            ],
        ),
        migrations.CreateModel(
            name='CardInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_list', models.ManyToManyField(through='CardCrab.CardInCart', to='CardCrab.Card')),
            ],
        ),
        migrations.CreateModel(
            name='PlayFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cardincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.Cart'),
        ),
        migrations.AddField(
            model_name='carddetails',
            name='formats',
            field=models.ManyToManyField(to='CardCrab.PlayFormat'),
        ),
        migrations.AddField(
            model_name='carddetails',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardRarity'),
        ),
        migrations.AddField(
            model_name='carddetails',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardSet'),
        ),
        migrations.AddField(
            model_name='carddetails',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardType'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardDetails'),
        ),
        migrations.AddField(
            model_name='card',
            name='printing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardPrint'),
        ),
        migrations.AddField(
            model_name='card',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.Seller'),
        ),
        migrations.AddField(
            model_name='card',
            name='wear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardWear'),
        ),
    ]
