# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardCrab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='art',
        ),
        migrations.AddField(
            model_name='card',
            name='print',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carddetails',
            name='back_art',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carddetails',
            name='front_art',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.Seller'),
        ),
    ]
