# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardCrab', '0003_auto_20170315_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardSet'),
        ),
    ]
