# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardCrab', '0005_cardcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='color',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='color',
            field=models.ManyToManyField(to='CardCrab.CardColor'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardRarity'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardType'),
        ),
    ]
