# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardCrab', '0006_auto_20170315_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='condition',
        ),
        migrations.AlterField(
            model_name='card',
            name='print',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardPrint'),
        ),
        migrations.AddField(
            model_name='card',
            name='wear',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CardCrab.CardWear'),
            preserve_default=False,
        ),
    ]
