# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardCrab', '0007_auto_20170315_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
